spring:
    data:
        mongodb:
            database: online_shopping
            port: 27017
            host: localhost
#            authentication-database: admin
#            username: mwa
server:
    port: 8080
#            password: cs572

jwt.secret.key: minte
jwt.expiration.time: 1000000